// All interpolated markup is authored UI copy; history data is inserted via textContent.
const icon = (name, className = '') => `<img class="ui-icon ${className}" src="icons/ui/${name}.svg" alt="" aria-hidden="true">`;

export function view(t, compact, modal = false) {
  const language = `<div id="language" class="language-switch" role="group" aria-label="${t('language')}"><button type="button" data-language="en" lang="en" aria-label="English" aria-pressed="false">EN</button><button type="button" data-language="zh-CN" lang="zh-CN" aria-label="简体中文" aria-pressed="false">中文</button></div>`;
  const brandTag = modal ? 'div' : 'a';
  const brand = `<${brandTag} class="brand"${modal ? '' : ' href="manager.html"'}><img class="brand-mark" src="icons/mark-premium.png" width="40" height="40" alt=""><span class="brand-copy"><strong>History Sweep</strong><small>${t('tagline')}</small></span></${brandTag}>`;
  const privacy = `<span class="local-dot privacy-badge" title="${t('privacyBody')}">${t('local')}</span>`;
  const openButton = `<button id="openFull" class="icon-button" type="button" title="${t('full')}" aria-label="${t('full')}">${icon('arrow-square-out')}</button>`;
  const preferences = `<button id="openPreferences" class="icon-button" type="button" title="${t('preferences')}" aria-label="${t('preferences')}">${icon('gear')}</button>`;

  const filters = `<div class="filter-toolbar"><details id="filters" class="filters"><summary id="filterToggle" aria-label="${t('filters')}" title="${t('filters')}">${icon('sliders')}<span class="filter-label">${t('filters')}</span><span id="filterSummary"></span></summary><div class="filters-body"><label class="time-field"><span>${t('timeLabel')}</span><span class="time-select"><select id="timeRange" aria-label="${t('timeLabel')}"><button type="button"><selectedcontent></selectedcontent></button><option value="all">${t('timeAll')}</option><option value="today">${t('timeToday')}</option><option value="7days">${t('timeWeek')}</option><option value="30days">${t('timeMonth')}</option><option value="custom">${t('timeCustom')}</option></select></span></label><div id="customDates" class="custom-dates" hidden><label><span>${t('startDate')}</span><span class="date-control"><input id="startDate" class="date-input" type="text" inputmode="numeric" maxlength="10" placeholder="${t('calendarPlaceholder')}" autocomplete="off" spellcheck="false"><button type="button" class="calendar-toggle" data-calendar-for="startDate" aria-label="${t('calendarOpen', { label: t('startDate') })}" aria-haspopup="dialog" aria-controls="datePicker" aria-expanded="false">${icon('calendar')}</button></span></label><label><span>${t('endDate')}</span><span class="date-control"><input id="endDate" class="date-input" type="text" inputmode="numeric" maxlength="10" placeholder="${t('calendarPlaceholder')}" autocomplete="off" spellcheck="false"><button type="button" class="calendar-toggle" data-calendar-for="endDate" aria-label="${t('calendarOpen', { label: t('endDate') })}" aria-haspopup="dialog" aria-controls="datePicker" aria-expanded="false">${icon('calendar')}</button></span></label></div><p class="filter-hint">${t('timeHint')}</p><button id="editProtection" class="quiet" type="button">${t('keptSites', { n: 0 })}</button></div></details>${compact ? `<button id="currentSite" class="quiet current-site" type="button">${t('currentSite')}</button>` : ''}</div>`;

  return `<main class="app-shell">
    <header class="topbar">${brand}<div class="top-actions">${compact || modal ? '' : privacy}${language}${preferences}${compact || modal ? openButton : `<span class="version">v0.3.2</span>`}</div></header>
    <h1 class="sr-only">${t('heading')}</h1>
    <div id="updateSlot" class="update-slot" data-open="false" hidden inert><div class="update-clip"><section id="updateBanner" class="update-banner" aria-label="${t('extensionUpdate')}">${icon('arrows-clockwise')}<span id="updateCopy" class="update-copy" role="status" aria-live="polite"></span><div class="update-actions"><button id="applyUpdate" class="primary" type="button">${t('updateNow')}</button><button id="dismissUpdate" class="quiet" type="button">${t('updateLater')}</button></div></section></div></div>
    <section class="search-workspace">
    <form id="searchForm" class="search-panel">
      <div class="query-field"><label for="query">${t('searchLabel')}</label><div class="input-wrap">${icon('magnifying-glass')}<input id="query" type="text" required autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="suggestionsList" aria-label="${t('searchLabel')}" placeholder="${t('placeholder')}"><button id="clearQuery" class="clear-query" type="button" aria-label="${t('clearQuery')}" hidden>${icon('x')}</button><details class="search-help"><summary aria-label="${t('searchHelp')}" title="${t('searchHelp')}">?</summary><p class="search-hint">${t('searchHint')}</p></details><div id="suggestionsPanel" class="suggestions-panel" data-open="false" inert><div class="suggestions-heading">${t('suggestions')}<span>Top 10</span></div><div id="suggestionsList" class="suggestions-list" role="listbox" aria-label="${t('suggestions')}"></div><p class="suggestions-hint">${t('suggestionsHint')}</p></div></div></div>
      <label class="mode-field"><span>${t('modeLabel')}</span><select id="mode" aria-label="${t('modeLabel')}"><button type="button"><selectedcontent></selectedcontent></button><option value="smart">${t('smart')}</option><option value="host-subdomains">${t('domains')}</option><option value="host-exact">${t('exact')}</option><option value="contains">${t('contains')}</option></select></label>
      ${compact ? '' : filters}
      <button class="primary" id="search" type="submit">${icon('magnifying-glass')}<span>${t('scan')}</span></button>
    </form>
    ${compact ? filters : ''}
    </section>
    <p id="protectedCount" class="protected-count" hidden></p>
    <section class="results-panel">
      <div class="results-heading"><div class="results-count"><h2 id="count">${t('resultCount', { n: 0 })}</h2>${compact ? '<span id="siteCount" hidden></span>' : ''}</div><div class="grouping-toolbar"><button id="groupBySite" class="quiet group-view" type="button" aria-pressed="true" hidden>${t('groupBySite')}</button><button id="expandGroups" class="quiet" type="button" hidden>${t('expandAll')}</button></div></div>
      <div class="toolbar selection-toolbar">${compact ? '' : '<span id="siteCount" hidden></span>'}<span id="selected"${compact ? '' : ' class="sr-only"'}>0 ${t('selected')}</span><button id="selectAll" class="quiet select-all" disabled>${icon('check-square')}<span id="selectAllLabel">${t(compact ? 'selectAllCompact' : 'selectAll', { n: 0 })}</span></button><button id="clear" class="quiet" disabled>${t('clear')}</button></div>
      <div id="resultScroll" class="result-scroll"><div id="empty" class="empty">${icon('magnifying-glass','empty-icon')}<h3>${t('emptyTitle')}</h3><p>${t('emptyBody')}</p></div><div id="groups" class="website-groups" hidden></div><table id="table" hidden><thead><tr><th><span class="sr-only">${t('selected')}</span></th><th>${t('page')}</th><th class="date-column">${t('lastVisit')}</th><th class="visit-column">${t('visits')}</th><th class="row-actions"><span class="sr-only">${t('deleteRow')}</span></th></tr></thead><tbody id="rows"></tbody></table><button id="loadMore" class="quiet more" hidden>${t('loadMore')}</button></div>
      <p id="preview" class="preview" hidden></p>
    </section>
    <div class="status-area"><progress id="progress" value="0" max="1" aria-label="${t('progress')}" hidden></progress><p id="status" role="status" aria-live="polite">${t('ready')}</p></div>
    <footer class="actionbar">${compact ? `<button id="openFullFooter" class="secondary-action" type="button">${icon('arrow-square-out')}<span>${t('full')}</span></button>` : `<div id="selectionSummary" class="selection-summary"><strong id="footerSelected"></strong><span id="selectedSites"></span></div><div id="selectedSiteChips" class="selected-site-chips"></div>`}<span class="delete-note">${t('deleteNote')}</span><button id="delete" class="delete" disabled>${icon('trash')}<span id="deleteLabel">${t('delete')}</span></button></footer>
    <div id="completionFeedback" class="completion-feedback" aria-hidden="true" hidden><div class="completion-orbit">${icon('check')}</div><div class="completion-copy"><div class="completion-heading"><strong id="completionCount" class="completion-count"></strong><span class="completion-title">${t('completionTitle')}</span></div><span class="completion-detail">${t('completionDetail')}</span></div></div>
  </main>
  <dialog id="confirmDialog" aria-labelledby="confirmTitle" aria-describedby="confirmBody"><form method="dialog"><div class="dialog-symbol">${icon('trash')}</div><h2 id="confirmTitle">${t('confirmTitle')}</h2><p id="confirmBody"></p><p id="previewTimeWarning" class="preview-time-warning" hidden>${t('previewTimeWarning')}</p><section class="deletion-preview" aria-labelledby="previewTitle"><h3 id="previewTitle">${t('previewTitle')}</h3><p id="previewSummary"></p><div id="deletePreview" class="delete-preview"></div></section><p class="keep-open">${t('keepOpen')}</p><div class="dialog-actions"><button value="cancel" autofocus>${t('cancel')}</button><button class="delete" value="confirm">${icon('trash')}<span>${t('confirm')}</span></button></div></form></dialog>
  <dialog id="protectionDialog" aria-labelledby="protectionTitle" aria-describedby="protectionHint"><form id="protectionForm"><h2 id="protectionTitle">${t('protectionTitle')}</h2><p id="protectionHint">${t('protectionHint')}</p><label class="protection-label" for="protectionInput">${t('protectionLabel')}</label><textarea id="protectionInput" rows="5" maxlength="20000" autocomplete="off" spellcheck="false" placeholder="${t('protectionPlaceholder')}"></textarea><p id="protectionStatus" role="status" aria-live="polite"></p><div class="dialog-actions"><button id="closeProtection" type="button">${t('closeProtection')}</button><button id="saveProtection" class="primary" type="submit">${t('saveProtection')}</button></div></form></dialog>
  <dialog id="preferencesDialog" class="preferences-dialog" aria-labelledby="preferencesTitle"><form id="preferencesForm"><h2 id="preferencesTitle">${t('preferences')}</h2><p>${t('launchHint')}</p><fieldset id="launchChoices" class="launch-choices" disabled><legend class="sr-only">${t('launchMethod')}</legend>${['popup', 'modal', 'fullpage'].map(mode => `<label class="launch-choice"><input type="radio" name="launchMode" value="${mode}" required><span><strong>${t(`launch_${mode}`)}</strong><small>${t(`launch_${mode}_description`)}</small></span></label>`).join('')}</fieldset><p id="preferencesStatus" class="preferences-status" role="status" aria-live="polite"></p><div class="dialog-actions"><button id="closePreferences" type="button">${t('preferencesCancel')}</button><button id="savePreferences" class="primary" type="submit" disabled>${t('preferencesSave')}</button></div></form></dialog>
  <dialog id="openFullDialog" aria-labelledby="openFullTitle" aria-describedby="openFullBody"><form method="dialog"><div class="dialog-symbol dialog-symbol-info">${icon('arrow-square-out')}</div><h2 id="openFullTitle">${t('openFullTitle')}</h2><p id="openFullBody">${t('openFullBody')}</p><div class="dialog-actions"><button value="cancel" autofocus>${t('keepSelection')}</button><button class="primary" value="confirm">${t('full')}</button></div></form></dialog>`;
}
