import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dependency } from './runtime.mjs';
import { createServer } from './serve.mjs';
import { installMock, demoHistory } from './fixtures.mjs';
const {chromium}=dependency('playwright');
const root=fileURLToPath(new URL('../',import.meta.url));
await mkdir(root+'test-results',{recursive:true});
const server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true, ...(process.env.HISTORY_SWEEP_CHROME ? {executablePath:process.env.HISTORY_SWEEP_CHROME} : {})});
const errors=[]; let checks=0;
function check(value,message){assert.ok(value,message);checks++;}
try{
 for(const layout of ['manager','popup']){
   const context=await browser.newContext({viewport:layout==='popup'?{width:440,height:590}:{width:1280,height:800},locale:'zh-CN'});
   const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await installMock(page);
   await page.goto(origin+'/extension/'+layout+'.html');
   check(await page.locator('html').getAttribute('lang')==='en','default English even on Chinese browser');
   check(await page.getByRole('textbox',{name:'Find in your history',exact:true}).count()===1,'search input has an accessible name');
   check(await page.getByRole('combobox',{name:'Match by',exact:true}).count()===1,'match mode has an accessible name');
   await page.locator('#query').fill('X');await page.locator('#search').click();
   await page.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('124'));
   check(await page.locator('#openFullFooter').count()===(layout==='popup'?1:0),'open full page action appears only in popup');
   check(!(await page.locator('#empty').isVisible()),'empty state hidden with results');
   await page.locator('#selectAll').click();
   check(await page.evaluate(()=>document.querySelector('#delete').getBoundingClientRect().bottom<=innerHeight),'selected action visible without scrolling');
   check((await page.locator('#selected').textContent()).startsWith('124'),'select all includes non-rendered rows');
   check(await page.locator('#selectAllLabel').textContent()==='Deselect all' && await page.locator('#selectAll').getAttribute('aria-pressed')==='true','select all offers deselection');
   await page.locator('#selectAll').click();
   check((await page.locator('#selected').textContent()).startsWith('0') && await page.locator('input[type=checkbox]:checked').count()===0,'second click deselects every match');
   check((await page.locator('#selectAllLabel').textContent()).startsWith('Select all'),'select all label returns after deselection');
   await page.locator('#selectAll').focus();await page.keyboard.press('Space');
   check((await page.locator('#selected').textContent()).startsWith('124'),'keyboard selects every match');
   await page.keyboard.press('Space');
   check((await page.locator('#selected').textContent()).startsWith('0'),'keyboard deselects every match');
   await page.locator('#selectAll').click();
   await page.locator('#rows tr').first().locator('.page-title').click();
   check((await page.locator('#selected').textContent()).startsWith('123'),'clicking a result row deselects it');
   await page.locator('#rows tr').first().locator('.page-title').click();
   check((await page.locator('#selected').textContent()).startsWith('124'),'clicking a result row selects it again');
   await page.locator('input[type=checkbox]').first().uncheck();
   check((await page.locator('#selected').textContent()).startsWith('123'),'exclude one row');
   if(layout==='popup'){
     await page.locator('#openFull').click();
     check(await page.locator('#openFullDialog').evaluate(node=>node.open) && (await page.locator('#openFullDialog').textContent()).includes('will not carry over'),'popup explains that opening full page resets selection');
     check(await page.locator('#openFullDialog [value=cancel]').evaluate(node=>node===document.activeElement),'handoff dialog focuses the safe action');
     await page.locator('#openFullDialog [value=cancel]').click();
     check(await page.evaluate(()=>window.__opened.length)===0 && (await page.locator('#selected').textContent()).startsWith('123'),'canceling full-page handoff preserves selection');
     await page.locator('#openFullFooter').click();await page.locator('#openFullDialog [value=confirm]').click();
     await page.waitForFunction(()=>window.__opened.length===1);
     check(await page.evaluate(()=>!window.__opened[0].includes('?') && window.__messages.some(m=>m.type==='open-workspace' && m.query==='X')),'handoff keeps query in memory, not tab URL');
   }
   await page.locator('#query').fill('Y');
   check(await page.locator('#delete').isDisabled() && await page.locator('input[type=checkbox]').first().isDisabled(),'edited search prevents deleting stale results');
   check((await page.locator('#status').textContent()).includes('Search conditions changed'),'edited search explains stale results');
   await page.getByRole('button',{name:'简体中文',exact:true}).click();
   check(await page.locator('#query').inputValue()==='Y' && await page.locator('#delete').isDisabled(),'language switch preserves unsubmitted search and deletion guard');
   await page.locator('#query').fill('X');
   check(await page.locator('#delete').isEnabled() && (await page.locator('#selected').textContent()).includes('123 条已选'),'restoring search preserves selection');
   await page.locator('#mode').selectOption('contains');
   check(await page.locator('#delete').isDisabled(),'changed match mode prevents deleting stale results');
   await page.locator('#mode').selectOption('smart');
   check(await page.locator('#delete').isEnabled(),'restoring match mode re-enables deletion');
   await page.getByRole('button',{name:'English',exact:true}).click();
   await page.locator('#resultScroll').evaluate(node=>{node.scrollTop=100;});
   await page.getByRole('button',{name:'简体中文',exact:true}).click();
   check(await page.getByRole('button',{name:'简体中文',exact:true}).getAttribute('aria-pressed')==='true','Chinese language button selected');
   check(await page.locator('#query').inputValue()==='X' && await page.locator('#mode').inputValue()==='smart','language switch preserves query and mode');
   check(await page.locator('#resultScroll').evaluate(node=>node.scrollTop)===100,'language switch preserves result scroll');
   check(await page.locator('#query').getAttribute('placeholder')==='试试 X、x.com 或关键词','Chinese search placeholder');
   check(await page.getByRole('textbox',{name:'搜索浏览历史',exact:true}).count()===1 && await page.getByRole('combobox',{name:'匹配方式',exact:true}).count()===1,'accessible field names follow Chinese locale');
   check((await page.locator('#selected').textContent()).includes('123 条已选'),'language switch preserves selection');
   await page.getByRole('button',{name:'English',exact:true}).focus();await page.keyboard.press('Enter');
   check(await page.locator('html').getAttribute('lang')==='en' && await page.getByRole('button',{name:'English',exact:true}).evaluate(node=>node===document.activeElement),'keyboard language switch keeps focus');
   check((await page.locator('#selected').textContent()).includes('123 selected'),'English selection count');
   await page.locator('#delete').click();
   check(await page.locator('#confirmBody').textContent().then(text=>text.includes('123')),'English confirmation keeps selected count');
   await page.locator('#confirmDialog [value=cancel]').click();
   await page.getByRole('button',{name:'简体中文',exact:true}).click();
   await page.locator('#delete').click();
   check(await page.locator('#confirmTitle').textContent()==='确定告别这些页面？' && await page.locator('#confirmDialog [value=confirm]').textContent()==='永久删除','Chinese deletion confirmation');
   await page.locator('#confirmDialog [value=cancel]').click();
   check(await page.evaluate(()=>window.__deleted.length)===0,'cancel never deletes');
   await page.locator('#delete').click();await page.locator('#confirmDialog [value=confirm]').click();
   await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('已删除 123'));
   check(await page.locator('#count').textContent()==='1 条结果','kept excluded page');
   check(await page.evaluate(()=>window.__deleted.every(url=>url.startsWith('https://x.com/'))),'never deletes unrelated URL');
   await page.locator('#query').fill('not-found.example');await page.locator('#search').click();
   await page.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('0'));
   check(await page.locator('#empty').isVisible(),'zero-result state visible');
   check(!(await page.locator('#table').isVisible()),'table hidden for zero results');
   check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow');
   if(layout==='popup'){
     check(await page.evaluate(()=>document.querySelector('#delete').getBoundingClientRect().bottom<=innerHeight),'popup action visible');
     await page.locator('#openFull').click();
     await page.waitForFunction(()=>window.__opened.length===2);
     check(await page.evaluate(()=>!window.__opened.at(-1).includes('not-found.example') && window.__messages.at(-1).query==='not-found.example'),'full-page handoff excludes search term from URL');
   }
   await page.reload();check(await page.locator('html').getAttribute('lang')==='zh-CN','language persisted');
   await context.close();
 }
 const busy=await browser.newPage({viewport:{width:440,height:590}});await installMock(busy);
 await busy.goto(origin+'/extension/popup.html');
 await busy.evaluate(()=>{chrome.history.search=()=>new Promise(resolve=>{window.__finishSearch=resolve;});});
 await busy.locator('#query').fill('X');await busy.locator('#search').click();
 check(await busy.locator('#language button:disabled').count()===2,'language controls disabled during history operation');
 await busy.evaluate(()=>window.__finishSearch([]));
 await busy.waitForFunction(()=>!document.querySelector('#search').disabled);
 check(await busy.locator('#language button:disabled').count()===0,'language controls enabled after history operation');
 await busy.close();
 const failures=await browser.newPage({viewport:{width:1280,height:800}});await installMock(failures,demoHistory.slice(0,3));
 await failures.goto(origin+'/extension/manager.html');await failures.locator('#query').fill('X');await failures.locator('#search').click();await failures.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('3'));
 await failures.evaluate(url=>window.__failDelete=url,demoHistory[0].url);
 await failures.locator('#selectAll').click();await failures.locator('#delete').click();await failures.locator('#confirmDialog [value=confirm]').click();
 await failures.waitForFunction(()=>document.querySelector('#status').textContent.includes('could not be verified'));
 check((await failures.locator('#selected').textContent()).startsWith('1'),'failed URL remains selected');
 await failures.evaluate(()=>{window.__failDelete=null;window.__failVerify=true;});
 await failures.locator('#delete').click();await failures.locator('#confirmDialog [value=confirm]').click();
 await failures.waitForFunction(()=>document.querySelector('#status').textContent.includes('verification failed'));
 check(!(await failures.locator('#status').textContent()).includes('Verified:'),'never claims successful verification on failure');
 await failures.close();
 const handoff=await browser.newPage({viewport:{width:1280,height:800}});await installMock(handoff);
 await handoff.goto(origin+'/extension/manager.html#handoff=expired-fixture');
 await handoff.waitForFunction(()=>document.querySelector('#status').textContent.includes('Could not transfer'));
 check(new URL(handoff.url()).hash==='' && new URL(handoff.url()).search==='','handoff metadata removed from the visible URL');
 check(await handoff.locator('#query').inputValue()==='' && await handoff.locator('#search').isEnabled(),'expired handoff is explicit and allows a new search');
 await handoff.close();
 const stale=await browser.newPage({viewport:{width:440,height:590}});await installMock(stale,demoHistory.slice(0,2));
 await stale.goto(origin+'/extension/popup.html');await stale.locator('#query').fill('X');await stale.locator('#search').click();
 await stale.waitForFunction(()=>document.querySelector('#rows tr'));await stale.locator('#selectAll').click();
 await stale.evaluate(()=>{window.__backgroundUnavailable=true});
 for(const lang of ['en','zh-CN']){
   await stale.getByRole('button',{name:lang==='en'?'English':'简体中文',exact:true}).click();
   await stale.locator('#delete').click();await stale.locator('#confirmDialog [value=confirm]').click();
   await stale.waitForFunction(()=>document.querySelector('#status').dataset.kind==='reloadExtension');
   check((await stale.locator('#status').textContent()).includes('chrome://extensions'),'missing background gives reload instructions in '+lang);
   check(await stale.locator('#status').evaluate(node=>node.scrollWidth<=node.clientWidth && node.scrollHeight<=node.clientHeight),'reload instructions are fully visible in '+lang);
   check(await stale.locator('#delete').isEnabled() && await stale.evaluate(()=>window.__deleted.length===0),'missing background keeps selection and never reports deletion in '+lang);
 }
 await stale.locator('#query').fill('not-found.example');await stale.locator('#search').click();await stale.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('0'));
 await stale.locator('#openFull').click();await stale.waitForFunction(()=>document.querySelector('#status').dataset.kind==='reloadExtension');
 check(await stale.evaluate(()=>window.__opened.length===0),'missing background never opens a misleading workspace');
 await stale.close();
 const bulk=await browser.newPage({viewport:{width:1280,height:800}});
 await installMock(bulk,Array.from({length:100001},(_,i)=>({url:'https://bulk.example.test/'+i,title:'Synthetic page '+i,lastVisitTime:1700000000000-i,visitCount:1})));
 await bulk.goto(origin+'/extension/manager.html');await bulk.locator('#query').fill('bulk.example.test');await bulk.locator('#mode').selectOption('host-exact');
 const scanStarted=Date.now();await bulk.locator('#search').click();await bulk.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('100,000'));
 console.log('100,000 URL synthetic scan completed in '+(Date.now()-scanStarted)+'ms on this machine.');
 check((await bulk.locator('#status').textContent()).includes('Scan limit reached'),'scan limit is disclosed');
 check(await bulk.locator('#rows tr').count()===100,'large scan keeps initial rendering bounded');
 await bulk.locator('#selectAll').click();check((await bulk.locator('#selected').textContent()).startsWith('100,000'),'large selection includes all scanned matches');
 await bulk.locator('#delete').click();check((await bulk.locator('#confirmBody').textContent()).includes('100,000'),'large batch still requires explicit confirmation');
 await bulk.locator('#confirmDialog [value=cancel]').click();check(await bulk.evaluate(()=>window.__deleted.length)===0,'large batch cancellation never deletes');
 await bulk.close();
 for(const width of [390,320]){
   const mobile=await browser.newPage({viewport:{width,height:844}});await installMock(mobile);
   await mobile.goto(origin+'/extension/manager.html');await mobile.locator('#query').fill('X');await mobile.locator('#search').click();
   await mobile.waitForFunction(()=>document.querySelector('#count').textContent.startsWith('124'));
   const mobileLayout=await mobile.evaluate(()=>{const count=document.querySelector('#count').getBoundingClientRect();const toolbar=document.querySelector('.toolbar').getBoundingClientRect();const mode=document.querySelector('#mode').getBoundingClientRect();const search=document.querySelector('#search').getBoundingClientRect();return {countHeight:count.height,toolbarTop:toolbar.top,countBottom:count.bottom,modeBottom:mode.bottom,searchTop:search.top,scrollWidth:document.documentElement.scrollWidth,width:innerWidth};});
   check(mobileLayout.countHeight<40 && mobileLayout.toolbarTop>=mobileLayout.countBottom,'mobile results heading stays above selection controls');
   check(mobileLayout.scrollWidth<=mobileLayout.width,'mobile manager has no horizontal overflow');
   if(width===320) check(mobileLayout.searchTop>=mobileLayout.modeBottom,'narrow manager stacks full-width search controls');
   await mobile.close();
 }
 for(const width of [1440,390]){
   const page=await browser.newPage({viewport:{width,height:1000}});page.on('pageerror',e=>errors.push(e.message));
   const response=await page.goto(origin+'/site/');check(response.status()===200,'website serves');
   const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>e.tagName+'.'+e.className)}));
   check(overflow.scroll<=overflow.width,'responsive site no horizontal overflow '+JSON.stringify(overflow));
   check(await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete && i.naturalWidth>0)),'all website images loaded');
   await page.screenshot({path:root+'test-results/site-'+width+'.png',fullPage:true});
   if(width===1440) await page.screenshot({path:root+'test-results/site-hero.png'});
   await page.getByRole('button',{name:'简体中文',exact:true}).click();
   check(await page.locator('h1').textContent()==='留一点过去，多一点空间。','site Chinese translation');
   await page.goto(origin+'/site/privacy.html');check(await page.locator('html').getAttribute('lang')==='zh-CN','privacy follows language');
   check(!(await page.locator('main').textContent()).includes('What it processes'),'privacy content localized');
   await page.close();
 }
 check(!errors.length,'no runtime errors: '+errors.join('; '));
 console.log(checks+' browser assertions passed. Mock history only; no real browser profile accessed.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
